import { GoogleGenerativeAI } from '@google/generative-ai';
import { NextRequest, NextResponse } from 'next/server';

const MIN_CONTEXT_LENGTH = 50;
const MAX_CONTEXT_LENGTH = 5000;
const MAX_PROJECT_NAME_LENGTH = 200;

const DEMO_OUTPUTS: Record<string, string> = {
  'Project Charter': `# Project Charter: Demo Project

## Executive Summary
This project aims to establish a unified data platform consolidating customer interactions across all business channels. Expected to reduce reporting time by 60% and increase customer retention by 15% within the first year of operation.

## Business Objectives
| # | Objective | Success Metric | Target | Timeline |
|---|-----------|---------------|--------|----------|
| 1 | Unified customer view | Data completeness score | 95% | Q3 2026 |
| 2 | Real-time analytics | Dashboard refresh rate | < 5 min | Q2 2026 |
| 3 | Reduce data silos | Systems integrated | 5/5 | Q4 2026 |
| 4 | Improve data quality | Error rate | < 2% | Q3 2026 |
| 5 | Self-service BI | User adoption rate | 80% | Q1 2027 |

## Scope Definition
### In-Scope
- Integration of CRM, e-commerce, and support data sources
- Real-time dashboard development for executive stakeholders
- Automated data quality monitoring and alerting framework
- Self-service analytics layer for business users
- GDPR compliance framework and data classification

### Out-of-Scope
- Legacy system decommissioning (separate initiative)
- Custom ML model development
- Third-party data procurement and enrichment

## Stakeholder Map & RACI
| Stakeholder | Role | R | A | C | I |
|------------|------|---|---|---|---|
| VP Marketing | Executive Sponsor | | ✓ | ✓ | |
| Head of Sales | Business Owner | ✓ | | ✓ | |
| CTO | Technical Approver | | ✓ | ✓ | |
| Data Engineering Lead | Technical Lead | ✓ | | | |
| Analytics Manager | End User Rep | | | ✓ | ✓ |
| Security Officer | Compliance | | | ✓ | ✓ |

## Risk Register
| Risk | Probability | Impact | Mitigation | Owner |
|------|------------|--------|-----------|-------|
| Data quality issues in source systems | High | High | Automated validation rules + reconciliation | Data Lead |
| Scope creep from business stakeholders | Medium | High | Change control board with weekly review | PM |
| Key resource availability (Data Eng Lead) | Medium | Medium | Cross-training plan + backup resource | PM |
| API rate limits on source systems | Low | Medium | Caching layer + incremental sync | Engineering |
| GDPR non-compliance | Low | Critical | Legal review at each phase gate | Security |

## Next Steps
| Action | Owner | Due Date | Status |
|--------|-------|----------|--------|
| Finalize data source inventory | Data Lead | Week 1 | Pending |
| Set up development environment | Engineering | Week 1 | Pending |
| Stakeholder kickoff meeting | PM | Week 1 | Scheduled |
| Security review initiation | Security | Week 2 | Pending |
| First sprint planning | PM | Week 2 | Pending |

---
*Generated by DataPM Toolkit (Demo Mode)*`,
};

const SYSTEM_INSTRUCTION = `You are a Principal Data Project Manager and PMO consultant with 15+ years at Fortune 500 companies (Amazon, Google, Meta, McKinsey). You write documents that get projects funded, stakeholders aligned, and teams unblocked.

DOCUMENT QUALITY STANDARDS — these are non-negotiable:

1. **Real PMO quality**: Every document must look like it came from a $500K consulting engagement, not a chatbot. Use specific numbers, real dates, named stakeholders, and concrete metrics.

2. **Markdown mastery**: Use proper markdown — # for H1, ## for H2, ### for H3. Tables MUST have | header | format | with |---| separator rows. Use **bold** for emphasis, - for bullets.

3. **No placeholders**: NEVER write [TBD], [placeholder], [insert here], or [your name]. If information isn't provided, make a reasonable professional assumption based on industry standards and note it.

4. **Specificity over generality**: Instead of "improve performance", write "reduce dashboard load time from 8s to <2s by Q3 2026". Instead of "key stakeholder", name them with titles from the context.

5. **Table depth**: Every table must have 5-8 rows minimum of substantive, differentiated content. Each row should provide unique value, not repeat variations of the same point.

6. **Actionable next steps**: End every document with a concrete "Next Steps" table: Action | Owner | Due Date | Status. Use specific week/date references.

7. **Professional tone**: Authoritative but accessible. Write like a senior consultant presenting to a C-suite audience who values their time. No filler, no fluff, no AI-sounding phrases like "it's important to note" or "in today's landscape".

8. **Output length**: 1000-2000 words. Comprehensive enough to be useful, focused enough to be read.

9. **Section headers**: Use clear, descriptive section headers that a busy executive can scan in 30 seconds to find what they need.

10. **Cross-referencing**: Reference specific systems, tools, stakeholders, and data sources mentioned in the context throughout the document — not just in one section.`;

const buildPrompt = (type: string, name: string, ctx: string): string => {
  const base = `${SYSTEM_INSTRUCTION}

Generate a **${type}** for project: "${name}"

PROJECT CONTEXT:
${ctx}

CRITICAL: Make every section specific to THIS project. Reference actual stakeholders, systems, data sources, and constraints from the context above. If something isn't specified, make a reasonable professional assumption based on the project type and note it as an assumption.

`;

  const templates: Record<string, string> = {
    'Project Charter': `${base}
You are writing a Project Charter that will be presented to the steering committee for project approval. This document must be compelling enough to secure budget and resources.

OUTPUT STRUCTURE (use exactly these markdown headings):

# Project Charter: ${name}

## Executive Summary
Write 4-5 sentences. State the business problem (quantified), the proposed solution, expected ROI/impact (with specific metrics), and timeline. This paragraph alone should convince a CFO to keep reading.

## Business Objectives
| # | Objective | Success Metric | Baseline | Target | Timeline | Owner |
|---|-----------|---------------|----------|--------|----------|-------|
Write 5-6 objectives. Each must be SMART: Specific, Measurable, Achievable, Relevant, Time-bound. Include current baseline where possible.

## Scope Definition
### In-Scope
List 6-8 specific deliverables as bullet points. Be concrete: "Salesforce CRM integration via REST API" not just "CRM integration".

### Out-of-Scope
List 4-5 explicit exclusions. These prevent scope creep — be specific about what this project does NOT include and why.

### Key Assumptions
List 4-5 assumptions that, if proven wrong, would change the project plan.

## Stakeholder Map & RACI
| Stakeholder | Title | Department | R | A | C | I | Engagement Level |
|------------|-------|------------|---|---|---|---|-----------------|
List 6-8 stakeholders. Use names from context. Add engagement level (High/Medium/Low). Ensure every deliverable has at least one R and one A.

## Data Sources & Integration Architecture
| Source System | Data Domain | Volume/Day | Latency Req. | Integration Method | Data Format | Quality Score | Owner |
|-------------|------------|-----------|-------------|-------------------|------------|--------------|-------|
List 4-6 sources based on context. Include realistic volumes and quality assessments.

## Project Timeline
| Phase | Duration | Start | End | Key Deliverables | Go/No-Go Criteria | Dependencies |
|-------|----------|-------|-----|-----------------|-------------------|-------------|
List 5-6 phases. Use specific date ranges (e.g., "Jan 15 – Feb 28, 2026"). Include clear go/no-go criteria for phase gates.

## Risk Register
| ID | Risk Description | Category | Probability | Impact | Risk Score | Mitigation Strategy | Contingency Plan | Owner | Trigger |
|----|-----------------|----------|------------|--------|-----------|--------------------|--------------------|-------|---------|
List 6-8 risks spanning: Technical, Resource, Data Quality, Compliance, Organizational, and Vendor categories. Risk Score = Probability × Impact (use H/M/L).

## Budget Overview
| Category | Estimated Cost | Notes | Confidence |
|----------|---------------|-------|-----------|
Include: Infrastructure/Cloud, Licensing, Internal Labor, External Consulting, Training, Contingency (15-20%). Show total.

## Governance & Decision Framework
Describe: decision-making authority matrix, escalation path (3 levels), steering committee cadence, change request process, and status reporting frequency.

## Success Criteria & Exit Conditions
Define what "done" looks like. List 4-5 measurable criteria that must be met before project closure.

## Next Steps (Immediate Actions)
| # | Action Item | Owner | Due Date | Priority | Status |
|---|------------|-------|----------|----------|--------|
List 5-6 concrete actions for the next 2 weeks.`,

    'KPI Framework': `${base}
You are designing a KPI framework that will drive executive decision-making and operational performance monitoring. Each KPI must be measurable with existing or planned data infrastructure.

OUTPUT STRUCTURE:

# KPI Framework: ${name}

## Framework Overview
3-4 sentences: What business outcomes this framework measures, who uses it, and how it connects to company OKRs/strategy.

## Strategic KPIs (Executive Level)
| KPI | Business Question It Answers | Formula/Calculation | Data Source | Baseline | Target | Owner | Frequency |
|-----|---------------------------|--------------------|-----------|---------|---------|---------|----|
5-6 strategic KPIs. Each should answer a specific business question a CEO/CFO would ask.

## Operational KPIs (Team Level)
| KPI | Definition | Formula | Source System | Current | Target | Owner | Frequency | Alert Threshold |
|-----|-----------|---------|-------------|---------|--------|-------|-----------|----------------|
5-6 operational KPIs with specific alert thresholds that trigger action.

## Data Quality KPIs
| Metric | What It Measures | Calculation | Threshold | Alert Action | Owner |
|--------|-----------------|-------------|-----------|-------------|-------|
4-5 data quality metrics: completeness, freshness, accuracy, consistency, uniqueness.

## Leading vs Lagging Indicators
| Leading Indicator | Lead Time | Predicts → | Lagging Indicator | Correlation |
|-------------------|-----------|-----------|-------------------|-------------|
Map 4-5 leading indicators to the lagging outcomes they predict.

## Dashboard Design Recommendations
### Executive Dashboard (Weekly Review)
- Layout: 4-6 key metrics with sparklines, RAG status, and week-over-week trend
- Key visualizations and what decisions they support

### Operational Dashboard (Daily)
- Layout: Real-time metrics, alerts panel, drill-down capability
- Key visualizations and alert configurations

### Deep Dive Dashboard (Ad-hoc Analysis)
- Layout: Filterable, date-range selectable, exportable
- Self-service analytics capabilities

## Review Cadence & Governance
| Review Type | Frequency | Attendees | Metrics Reviewed | Decision Authority | Format |
|------------|-----------|-----------|-----------------|-------------------|--------|

## Alerting & Escalation Matrix
| Severity | Condition | Notification | Response Time | Escalation Path |
|----------|-----------|-------------|--------------|----------------|

## Next Steps
| Action | Owner | Due Date |
|--------|-------|----------|`,

    'Data Specification': `${base}
You are writing a Data Specification document for a senior data engineering team. This document must be precise enough to implement from, with zero ambiguity on data types, business rules, and transformation logic.

OUTPUT STRUCTURE:

# Data Specification: ${name}

## Document Purpose & Audience
Who will use this spec (engineers, QA, analysts), versioning info, and review cycle.

## Source Systems Inventory
| System | Type | Protocol | Data Format | Volume (records/day) | Refresh Pattern | SLA | Owner | Access Method |
|--------|------|----------|------------|---------------------|----------------|-----|-------|--------------|
List 4-6 source systems with specific technical details.

## Conceptual Data Model
Describe the key entities, their relationships, and cardinality in text. Be specific: "Customer (1) → Orders (N) → Order_Items (N) → Products (1)"

## Entity: [Primary Entity — derive from context]
**Description:** What this entity represents in business terms
**Source:** Primary source system
**Volume:** Expected row count and growth rate
**Grain:** What one row represents
**Update Pattern:** Insert-only, SCD Type 2, full refresh, etc.

| # | Field Name | Data Type | Length/Precision | Business Description | Nullable | Default | Validation Rules | PII Classification | Source Field | Transformation |
|---|-----------|----------|-----------------|---------------------|----------|---------|-----------------|-------------------|-------------|---------------|
12-15 fields with complete technical specifications. Include realistic data types (VARCHAR(255), DECIMAL(10,2), TIMESTAMP WITH TIME ZONE, etc.)

## Entity: [Secondary Entity]
Same structure, 10-12 fields.

## Data Quality Rules
| Rule ID | Rule Name | Entity.Field | Business Rule Description | SQL/Logic Expression | Severity | Action on Failure | Threshold |
|---------|-----------|-------------|------------------------|---------------------|----------|------------------|-----------|
6-8 rules covering: NOT NULL, referential integrity, range checks, format validation, cross-field validation, business logic.

## Transformation Rules
| ID | Source | Target | Transformation Logic | Business Justification | Edge Cases |
|----|--------|--------|---------------------|----------------------|-----------|
6-8 transformations with actual logic (CASE statements, COALESCE, date conversions, etc.)

## Security & Privacy Classification
| Classification | Description | Fields | Access Control | Encryption | Retention |
|---------------|-----------|--------|---------------|-----------|-----------|
Define 3-4 classification levels and map fields to them.

## Data Lineage
Source → Staging → Transformation → Target for 2-3 key data flows. Include job names and scheduling.

## Integration Specifications
| Integration Point | Direction | Protocol | Format | Frequency | Retry Policy | Error Handling | SLA |
|-------------------|-----------|----------|--------|-----------|-------------|---------------|-----|

## Glossary
| Term | Business Definition | Technical Notes | Synonyms |
|------|-------------------|----------------|----------|
10-12 domain-specific terms.

## Next Steps
| Action | Owner | Due Date |
|--------|-------|----------|`,

    'Stakeholder Deck Outline': `${base}
You are writing a presentation outline for a high-stakes stakeholder meeting. Each slide must have clear talking points, specific data to present, and visual recommendations. The presenter should be able to create the deck from this outline alone.

OUTPUT STRUCTURE:

# Stakeholder Deck: ${name}

## Presentation Strategy
- **Target Audience:** Who's in the room, their concerns, and what they need to hear
- **Key Message:** The one sentence you want everyone to remember
- **Desired Outcome:** The specific decision or approval you're seeking
- **Duration:** Recommended presentation time with Q&A

## Slide 1: Title Slide
- **Title:** ${name}
- **Subtitle:** [Status] Update — [Date]
- **Presenter:** [Name, Title]
- **Visual:** Company logo + project logo, clean dark background
- **Duration:** 30 seconds

## Slide 2: Agenda & Context
- **Content:** 6-7 numbered agenda items with time allocations
- **Talking Point:** "We'll cover [X], focus on [Y], and need a decision on [Z]"
- **Visual:** Numbered list with progress indicator

## Slide 3: Executive Summary (The "So What" Slide)
- **Status:** Overall RAG status [Green/Yellow/Red] with one-sentence justification
- **Key Achievement This Period:** Most impressive result with specific metric
- **Critical Watch Item:** The one thing keeping you up at night
- **The Ask:** What you need from this audience (budget, decision, resources, air cover)
- **Talking Points:** 3-4 bullet points for verbal delivery
- **Visual:** RAG dashboard with 3 cards: Achievement | Watch Item | The Ask
- **Duration:** 2 minutes

## Slide 4: Business Impact & Value Delivered
- **Metrics to Show:** 3-4 quantified business outcomes achieved or projected
- **Before/After Comparison:** Concrete numbers showing improvement
- **Talking Points:** Frame as business value, not technical achievement
- **Visual:** Side-by-side comparison chart, or metric cards with trend arrows
- **Duration:** 2 minutes

## Slide 5: Architecture / Solution Overview
- **Content:** High-level view of what's being built
- **Talking Points:** Keep it simple — audience-appropriate technical depth
- **Visual:** Architecture diagram (boxes and arrows, not code)
- **Duration:** 1.5 minutes — don't over-explain

## Slide 6: Progress & Milestones
- **Completed:** 3-4 milestones with dates achieved
- **In Progress:** 2-3 items with % complete and expected completion
- **Upcoming:** 3-4 items with target dates
- **Talking Points:** Focus on what shipped, not what's planned
- **Visual:** Horizontal timeline or milestone tracker with RAG colors
- **Duration:** 2 minutes

## Slide 7: Key Metrics & KPIs
- **Metrics Grid:** 4-6 KPIs with current value, target, trend, and RAG status
- **Talking Points:** Call out what's improving and what needs attention
- **Visual:** KPI dashboard cards with sparkline trends
- **Duration:** 2 minutes

## Slide 8: Risks & Mitigations
- **Top 3 Risks:** Each with mitigation plan, owner, and timeline
- **Resolved Since Last Update:** 1-2 risks that were managed successfully
- **Talking Points:** Be transparent — stakeholders respect honesty
- **Visual:** 2×2 risk matrix (probability × impact) with risk dots
- **Duration:** 2 minutes

## Slide 9: Budget & Resource Status
- **Budget:** Planned vs Actual vs Forecast, with variance analysis
- **Resources:** Current team, utilization, any gaps
- **Talking Points:** Flag any budget concerns early
- **Visual:** Budget burn-down chart + resource heatmap
- **Duration:** 1.5 minutes

## Slide 10: Decisions Needed & Next Steps
- **Decisions Required:** 2-3 specific decisions for THIS audience
- **Next Milestones:** 3-4 items for next period
- **Action Items from This Meeting:** Who does what by when
- **Talking Points:** End strong — clear asks, confident delivery
- **Visual:** Action items table with owners and deadlines
- **Duration:** 2 minutes

## Slide 11: Appendix (Backup Slides)
- Detailed technical architecture
- Full risk register
- Complete budget breakdown
- Data quality metrics
- Team structure and RACI
- Vendor comparison (if applicable)`,

    'Data Dictionary': `${base}
OUTPUT STRUCTURE:

# Data Dictionary: ${name}

## Purpose & Scope
Who this dictionary serves, what systems it covers, and maintenance cadence.

## Business Glossary
| Term | Business Definition | Related Terms | Domain | Data Owner | Last Updated |
|------|-------------------|---------------|--------|-----------|-------------|
15 terms relevant to the project domain.

## Entity: [Primary Entity]
**Description:** Business purpose of this entity
**Source:** Origin system
**Volume:** Row count and growth rate
**Update Frequency:** How often this data changes

| # | Field Name | Business Name | Data Type | Length | Description | Valid Values/Rules | Required | PII | Source System | Example |
|---|-----------|---------------|-----------|--------|-------------|-------------------|----------|-----|-------------|---------|
12-15 fields with complete metadata.

## Entity: [Secondary Entity]
Same structure, 10-12 fields.

## Entity: [Tertiary Entity]
Same structure, 8-10 fields.

## Reference Data
| Code Set | Code | Display Value | Description | Status | Effective Date |
|----------|------|-------------|-----------|--------|---------------|

## Relationships
| Parent Entity | Child Entity | Relationship Type | Join Key | Cardinality | Enforced |
|--------------|-------------|------------------|----------|-------------|----------|

## Data Classification & Privacy
| Classification Level | Description | Example Fields | Handling Requirements | Retention Period |
|---------------------|-----------|---------------|---------------------|----------------|

## Change Log
| Version | Date | Author | Changes | Approved By |
|---------|------|--------|---------|------------|`,

    'Migration Plan': `${base}
OUTPUT STRUCTURE:

# Migration Plan: ${name}

## Migration Overview
Scope, approach (big bang/phased/parallel), success criteria, and risk tolerance.

## Current vs Target Architecture
| Dimension | Current State | Target State | Gap Analysis | Migration Complexity |
|-----------|--------------|-------------|-------------|---------------------|
8-10 comparison dimensions.

## Migration Strategy
### Approach Selection
Justify the chosen approach with pros/cons of alternatives.
### Fallback Strategy
What happens if migration fails at each phase gate.

## Data Mapping
| # | Source Table | Source Field | Source Type | Target Table | Target Field | Target Type | Transformation Rule | Notes |
|---|-------------|-------------|-----------|-------------|-------------|-----------|-------------------|-------|
12-15 key field mappings with actual transformation logic.

## Migration Phases
| Phase | Name | Duration | Start | End | Activities | Resources | Exit Criteria | Rollback Point |
|-------|------|----------|-------|-----|-----------|-----------|--------------|----------------|
5-6 phases with specific dates and criteria.

## Testing Strategy
### Unit Testing
| Test ID | Description | Input | Expected Output | Owner | Status |
|---------|-----------|-------|----------------|-------|--------|

### Integration Testing
| Scenario | Systems | Validation Method | Acceptance Criteria | Status |
|----------|---------|-----------------|-------------------|--------|

### UAT Plan
| Test Case | Business Process | User Role | Steps | Expected Result | Status |
|-----------|-----------------|----------|-------|----------------|--------|

## Validation & Reconciliation
| Check Type | Method | Source Count | Target Count | Tolerance | Action if Failed |
|-----------|--------|-------------|-------------|-----------|-----------------|
Include: row counts, checksums, referential integrity, business rules, date boundaries.

## Rollback Plan
Step-by-step rollback procedure with estimated time for each step.

## Cutover Checklist
15-20 checklist items with owners and timing.

## Communication Plan
| Timing | Audience | Message | Channel | Owner |
|--------|---------|---------|---------|-------|

## Post-Migration Monitoring (First 30 Days)
| Timeframe | What to Monitor | Success Criteria | Escalation Path |
|-----------|----------------|-----------------|----------------|

## Next Steps
| Action | Owner | Due Date |
|--------|-------|----------|`,

    'Requirements Document': `${base}
OUTPUT STRUCTURE:

# Requirements Document: ${name}

## Document Purpose
Scope, intended audience, requirements validation process.

## Business Requirements
| ID | Priority | Requirement | Business Value | Acceptance Criteria | Source |
|----|----------|------------|---------------|-------------------|--------|
8-10 business requirements with MoSCoW priority.

## Functional Requirements
### FR1: Data Ingestion
| ID | Requirement | Acceptance Criteria | Priority | Complexity | Dependencies |
|----|------------|-------------------|----------|-----------|-------------|
5-6 requirements.

### FR2: Data Processing & Transformation
| ID | Requirement | Acceptance Criteria | Priority | Complexity | Dependencies |
|----|------------|-------------------|----------|-----------|-------------|
5-6 requirements.

### FR3: Data Output & Reporting
| ID | Requirement | Acceptance Criteria | Priority | Complexity | Dependencies |
|----|------------|-------------------|----------|-----------|-------------|
4-5 requirements.

### FR4: User Interface
| ID | Requirement | Acceptance Criteria | Priority | Complexity | Dependencies |
|----|------------|-------------------|----------|-----------|-------------|
3-4 requirements.

## Non-Functional Requirements
| Category | ID | Requirement | Target Metric | Measurement Method | Priority |
|----------|---|------------|--------------|-------------------|----------|
Performance, Scalability, Security, Availability, Compliance, Maintainability — 2 each.

## User Stories
8-10 user stories in proper format:
### Epic: [Primary Capability]
**US-001:** As a [role], I want [capability], so that [benefit].
**Acceptance Criteria:**
- Given [context], when [action], then [result]
- Given [context], when [action], then [result]

## Integration Requirements
| System | Direction | Protocol | Format | Frequency | SLA | Error Handling |
|--------|-----------|----------|--------|-----------|-----|---------------|

## Constraints & Assumptions
### Constraints
### Assumptions

## Dependency Map
| Dependency | Type | Impact if Delayed | Mitigation | Owner |
|-----------|------|------------------|-----------|-------|

## Requirements Traceability Matrix
| Req ID | Test Case | Test Type | Status | Sign-off |
|--------|-----------|----------|--------|---------|

## Next Steps
| Action | Owner | Due Date |
|--------|-------|----------|`,
  };

  return templates[type] || `${base}\nGenerate a comprehensive ${type} document using proper markdown formatting with tables, headings, and bullet points. Aim for 1000-2000 words of substantive, professional content.`;
};

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { projectName, context, artifactType } = body;

    if (!projectName || !context || !artifactType) {
      return NextResponse.json({ error: 'All fields are required.' }, { status: 400 });
    }
    if (projectName.length > MAX_PROJECT_NAME_LENGTH) {
      return NextResponse.json({ error: `Project name too long (max ${MAX_PROJECT_NAME_LENGTH} chars).` }, { status: 400 });
    }
    if (context.length < MIN_CONTEXT_LENGTH) {
      return NextResponse.json({ error: `Please provide more context (minimum ${MIN_CONTEXT_LENGTH} characters).` }, { status: 400 });
    }
    if (context.length > MAX_CONTEXT_LENGTH) {
      return NextResponse.json({ error: `Context too long (max ${MAX_CONTEXT_LENGTH} chars).` }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      const demo = DEMO_OUTPUTS[artifactType] || DEMO_OUTPUTS['Project Charter']!;
      const content = demo.replace(/Demo Project/g, projectName);
      return NextResponse.json({ content, metadata: { wordCount: content.split(/\s+/).length, artifactType, generatedAt: new Date().toISOString(), demo: true } });
    }

    const prompt = buildPrompt(artifactType, projectName, context);
    const genAI = new GoogleGenerativeAI(apiKey);
    const MODELS = ['gemini-2.0-flash', 'gemini-1.5-flash'];
    let lastError = '';

    for (const modelName of MODELS) {
      for (let attempt = 0; attempt < 3; attempt++) {
        try {
          const model = genAI.getGenerativeModel({
            model: modelName,
            generationConfig: { temperature: 0.6, maxOutputTokens: 8192, topP: 0.85 },
          });
          const result = await model.generateContent(prompt);
          const text = result.response.text();
          if (text.length < 500) {
            if (attempt < 2) { await new Promise(r => setTimeout(r, 2000)); continue; }
            return NextResponse.json({ error: 'Generated output was too short. Please try again.' }, { status: 500 });
          }
          return NextResponse.json({ content: text, metadata: { wordCount: text.split(/\s+/).length, artifactType, generatedAt: new Date().toISOString(), model: modelName } });
        } catch (retryErr: unknown) {
          const errMsg = retryErr instanceof Error ? retryErr.message : String(retryErr);
          lastError = errMsg;
          if (errMsg.includes('429') && attempt < 2) {
            await new Promise(r => setTimeout(r, Math.pow(2, attempt + 1) * 2000));
            continue;
          }
          if (attempt < 2) { await new Promise(r => setTimeout(r, 2000)); continue; }
          break;
        }
      }
    }

    if (lastError.includes('429')) {
      const demo = DEMO_OUTPUTS[artifactType] || DEMO_OUTPUTS['Project Charter']!;
      const content = demo.replace(/Demo Project/g, projectName);
      return NextResponse.json({ content: content + '\n\n> ⚠️ *AI service at capacity — showing demo output. Try again in 30 seconds for AI-generated content.*', metadata: { wordCount: content.split(/\s+/).length, artifactType, generatedAt: new Date().toISOString(), demo: true } });
    }

    return NextResponse.json({ error: `Generation failed: ${lastError}` }, { status: 500 });
  } catch (err: unknown) {
    console.error('Generate error:', err);
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Unexpected error' }, { status: 500 });
  }
}
